MVC5Course-Homework1/Models/客戶資料.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Course_Homework1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶資料
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 客戶資料()
        {
            this.客戶銀行資訊 = new HashSet<客戶銀行資訊>();
            this.客戶聯絡人 = new HashSet<客戶聯絡人>();
        }
    
        public int Id { get; set; }
        public string 客戶名稱 { get; set; }
        public string 統一編號 { get; set; }
        public string 電話 { get; set; }
        public string 傳真 { get; set; }
        public string 地址 { get; set; }
        public string Email { get; set; }
        public bool 是否已刪除 { get; set; }
        public string 客戶分類 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶銀行資訊> 客戶銀行資訊 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶聯絡人> 客戶聯絡人 { get; set; }
    }
}

MVC5Course-Homework1/Controllers/客戶資料Controller.cs
namespace MVC5Course_Homework1.Controllers
{
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using MVC5Course_Homework1.Models;

    public class 客戶資料Controller : Controller
    {
        private 客戶資料Entities db = new 客戶資料Entities();

        // GET: 客戶資料
        public ActionResult Index(string keyword, string category)
        {
            var items = new List<string> { "全部" };
            items.AddRange(
                (from p in db.客戶資料
                 where p.是否已刪除 == false
                 select p.客戶分類)
                      .Distinct()
                      .OrderBy(x => x));

            ViewBag.可選分類 = new SelectList(items);

            var data = db.客戶資料.Where(p => p.是否已刪除 == false).AsQueryable();
            
            if (!string.IsNullOrEmpty(category) && category != "全部")
            {
                data = data.Where(p => p.客戶分類 == category);
            }

            if (string.IsNullOrEmpty(keyword))
            {
                return View(data.ToList());
            }

            data = data.Where(p => p.客戶名稱.Contains(keyword));
            return View(data.ToList());
        }

        // GET: 客戶資料/統計資料
        public ActionResult 統計資料()
        {
            var data = db.客戶統計資料檢視表;
            return View(data.ToList());
        }

        // GET: 客戶資料/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = db.客戶資料.Where(p => p.Id == id && p.是否已刪除 == false).SingleOrDefault();
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // GET: 客戶資料/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: 客戶資料/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶名稱,統一編號,電話,傳真,地址,Email")] 客戶資料 客戶資料)
        {
            if (ModelState.IsValid)
            {
                db.客戶資料.Add(客戶資料);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(客戶資料);
        }

        // GET: 客戶資料/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = db.客戶資料.Find(id);
            if (客戶資料 == null || 客戶資料.是否已刪除 == true)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: 客戶資料/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶分類,客戶名稱,統一編號,電話,傳真,地址,Email")] 客戶資料 客戶資料)
        {
            if (ModelState.IsValid)
            {
                db.Entry(客戶資料).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(客戶資料);
        }

        // GET: 客戶資料/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = db.客戶資料.Where(p => p.Id == id && p.是否已刪除 == false).SingleOrDefault();
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: 客戶資料/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶資料 客戶資料 = db.客戶資料.Find(id);
            客戶資料.是否已刪除 = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC5Course-Homework1/Views/客戶資料/Create.cshtml
@model MVC5Course_Homework1.Models.客戶資料

@{
    ViewBag.Title = "新增客戶資料";
}

<h2>新增客戶資料</h2>
<hr />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶分類, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶分類, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶分類, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到列表頁", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MVC5Course-Homework1/Views/客戶資料/Delete.cshtml
@model MVC5Course_Homework1.Models.客戶資料

@{
    ViewBag.Title = "刪除客戶資料" + Model.客戶名稱;
}

<h2>刪除客戶資料</h2>
<hr />

<h3>確認你要刪除這筆客戶資料?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶分類)
        </dt>

        <dd>
            @if (Model.客戶分類 == null)
            {
                <span>未分類</span>
            }
            else
            {
                @Html.DisplayFor(model => model.客戶分類)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="確認刪除" class="btn btn-default" /> |
            @Html.ActionLink("回到列表頁", "Index")
        </div>
    }
</div>

MVC5Course-Homework1/Views/客戶資料/Details.cshtml
@model MVC5Course_Homework1.Models.客戶資料

@{
    ViewBag.Title = "客戶資料 - 詳細內容";
}

<div>
    <h2>客戶資料 - 詳細內容</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶分類)
        </dt>

        <dd>
            @if (Model.客戶分類 == null)
            {
                <span>未分類</span>
            }
            else
            {
                @Html.DisplayFor(model => model.客戶分類)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("編輯", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("回到列表頁", "Index")
</p>

MVC5Course-Homework1/Views/客戶資料/Edit.cshtml
@model MVC5Course_Homework1.Models.客戶資料

@{
    ViewBag.Title = "編輯客戶資料";
}

<h2>編輯客戶資料</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶分類, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶分類, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶分類, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到列表頁", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MVC5Course-Homework1/Views/客戶資料/Index.cshtml
@model IEnumerable<MVC5Course_Homework1.Models.客戶資料>

@{
    ViewBag.Title = "客戶資料 - 列表頁";
}

<h2>客戶資料 - 列表頁</h2>

<p>
    @Html.ActionLink("新增客戶資料", "Create") |
    @Html.ActionLink("顯示統計資料", "統計資料")
</p>

@using (Html.BeginForm("Index", "客戶資料", FormMethod.Get))
{
    <input type="search" name="keyword" placeholder="請輸入關鍵字" class="form-control col-sm-4" />
    <button type="submit" class="btn btn-info">搜尋</button>
}

@using (Html.BeginForm("Index", "客戶資料", FormMethod.Get))
{
    var items = (SelectList) ViewBag.可選分類;

    @Html.DropDownList("category", items, "請選擇", new { @class = "form-control" })
    <button type="submit" class="btn btn-info">篩選</button>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.客戶分類)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.統一編號)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.電話)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.傳真)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.地址)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @if (item.客戶分類 == null)
            {
                <span>未分類</span>
            }
            else
            {
                @Html.DisplayFor(modelItem => item.客戶分類)
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.客戶名稱)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.統一編號)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.電話)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.傳真)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.地址)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("編輯", "Edit", new { id=item.Id }) |
            @Html.ActionLink("詳細內容", "Details", new { id=item.Id }) |
            @Html.ActionLink("刪除", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MVC5Course-Homework1/Views/客戶資料/統計資料.cshtml
@model IEnumerable<MVC5Course_Homework1.Models.客戶統計資料檢視表>

@{
    ViewBag.Title = "客戶資料 - 統計資料";
}

<h2>客戶資料 - 統計資料</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.聯絡人數量)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.銀行帳戶數量)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.客戶名稱)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.聯絡人數量)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.銀行帳戶數量)
        </td>
    </tr>
}

</table>

@Html.ActionLink("回到列表頁", "Index")